# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23c3d53d8cbb39e2694f7fbde6919f960609e3610dd1bffeebf82a4e6d4b92d6e765a595ea4df19cff1bed4a26caad7a26bcb21f59d327f32d3c34be90ee87d4

test:
  secret_key_base: 03664b8b4c61c93e68000f7ce5aa2d510197279b4a7534d5a9c233a7e3ef03d71120216c4f575c2a0275ef930b81f71af7170270a38f68d049fe37b49f349e1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
